import AsyncStorage from "@react-native-async-storage/async-storage";

export type CatalogueObject = {
  id: string;
  name: string;
  type: string;
  done: boolean;
  photoUri?: string;
  date?: string;
  notes?: string;
  // Metadonnees astronomiques
  constellation?: string;
  magnitude?: string;
  distance?: string;
  location?: { latitude: number; longitude: number };
};

export type Domain = {
  id: string;
  label: string;
  icon: string;
  color: string;
  objects: CatalogueObject[];
};

const STORAGE_KEY = "catalogue_data_v4";

const MESSIER: CatalogueObject[] = [
  {
    id: "m1",
    name: "M1 — Nebuleuse du Crabe",
    type: "Reste de supernova",
    done: false,
    constellation: "Taureau",
    magnitude: "8.4",
    distance: "6 500 al",
  },
  {
    id: "m2",
    name: "M2",
    type: "Amas globulaire",
    done: false,
    constellation: "Verseau",
    magnitude: "6.5",
    distance: "37 500 al",
  },
  {
    id: "m3",
    name: "M3",
    type: "Amas globulaire",
    done: false,
    constellation: "Chiens de chasse",
    magnitude: "6.2",
    distance: "33 900 al",
  },
  {
    id: "m4",
    name: "M4",
    type: "Amas globulaire",
    done: false,
    constellation: "Scorpion",
    magnitude: "5.6",
    distance: "7 200 al",
  },
  {
    id: "m5",
    name: "M5",
    type: "Amas globulaire",
    done: false,
    constellation: "Serpent",
    magnitude: "5.6",
    distance: "24 500 al",
  },
  {
    id: "m6",
    name: "M6 — Amas du Papillon",
    type: "Amas ouvert",
    done: false,
    constellation: "Scorpion",
    magnitude: "4.2",
    distance: "1 600 al",
  },
  {
    id: "m7",
    name: "M7 — Amas de Ptolemee",
    type: "Amas ouvert",
    done: false,
    constellation: "Scorpion",
    magnitude: "3.3",
    distance: "980 al",
  },
  {
    id: "m8",
    name: "M8 — Nebuleuse de la Lagune",
    type: "Nebuleuse en emission",
    done: false,
    constellation: "Sagittaire",
    magnitude: "6.0",
    distance: "4 100 al",
  },
  {
    id: "m9",
    name: "M9",
    type: "Amas globulaire",
    done: false,
    constellation: "Ophiuchus",
    magnitude: "7.7",
    distance: "25 800 al",
  },
  {
    id: "m10",
    name: "M10",
    type: "Amas globulaire",
    done: false,
    constellation: "Ophiuchus",
    magnitude: "6.6",
    distance: "14 300 al",
  },
  {
    id: "m11",
    name: "M11 — Amas du Canard Sauvage",
    type: "Amas ouvert",
    done: false,
    constellation: "Ecu de Sobieski",
    magnitude: "5.8",
    distance: "6 200 al",
  },
  {
    id: "m12",
    name: "M12",
    type: "Amas globulaire",
    done: false,
    constellation: "Ophiuchus",
    magnitude: "6.7",
    distance: "16 000 al",
  },
  {
    id: "m13",
    name: "M13 — Amas d'Hercule",
    type: "Amas globulaire",
    done: false,
    constellation: "Hercule",
    magnitude: "5.8",
    distance: "25 100 al",
  },
  {
    id: "m14",
    name: "M14",
    type: "Amas globulaire",
    done: false,
    constellation: "Ophiuchus",
    magnitude: "7.6",
    distance: "30 300 al",
  },
  {
    id: "m15",
    name: "M15",
    type: "Amas globulaire",
    done: false,
    constellation: "Pegase",
    magnitude: "6.2",
    distance: "33 600 al",
  },
  {
    id: "m16",
    name: "M16 — Nebuleuse de l'Aigle",
    type: "Nebuleuse en emission",
    done: false,
    constellation: "Serpent",
    magnitude: "6.0",
    distance: "7 000 al",
  },
  {
    id: "m17",
    name: "M17 — Nebuleuse Omega",
    type: "Nebuleuse en emission",
    done: false,
    constellation: "Sagittaire",
    magnitude: "6.0",
    distance: "5 500 al",
  },
  {
    id: "m18",
    name: "M18",
    type: "Amas ouvert",
    done: false,
    constellation: "Sagittaire",
    magnitude: "7.5",
    distance: "4 900 al",
  },
  {
    id: "m19",
    name: "M19",
    type: "Amas globulaire",
    done: false,
    constellation: "Ophiuchus",
    magnitude: "6.8",
    distance: "28 700 al",
  },
  {
    id: "m20",
    name: "M20 — Nebuleuse Trifide",
    type: "Nebuleuse en emission",
    done: false,
    constellation: "Sagittaire",
    magnitude: "6.3",
    distance: "5 200 al",
  },
  {
    id: "m21",
    name: "M21",
    type: "Amas ouvert",
    done: false,
    constellation: "Sagittaire",
    magnitude: "6.5",
    distance: "4 250 al",
  },
  {
    id: "m22",
    name: "M22",
    type: "Amas globulaire",
    done: false,
    constellation: "Sagittaire",
    magnitude: "5.1",
    distance: "10 600 al",
  },
  {
    id: "m23",
    name: "M23",
    type: "Amas ouvert",
    done: false,
    constellation: "Sagittaire",
    magnitude: "6.9",
    distance: "2 150 al",
  },
  {
    id: "m24",
    name: "M24 — Nuage du Sagittaire",
    type: "Nuage stellaire",
    done: false,
    constellation: "Sagittaire",
    magnitude: "4.6",
    distance: "10 000 al",
  },
  {
    id: "m25",
    name: "M25",
    type: "Amas ouvert",
    done: false,
    constellation: "Sagittaire",
    magnitude: "4.6",
    distance: "2 000 al",
  },
  {
    id: "m26",
    name: "M26",
    type: "Amas ouvert",
    done: false,
    constellation: "Ecu de Sobieski",
    magnitude: "8.0",
    distance: "5 000 al",
  },
  {
    id: "m27",
    name: "M27 — Nebuleuse Haltere",
    type: "Nebuleuse planetaire",
    done: false,
    constellation: "Petit Renard",
    magnitude: "7.4",
    distance: "1 360 al",
  },
  {
    id: "m28",
    name: "M28",
    type: "Amas globulaire",
    done: false,
    constellation: "Sagittaire",
    magnitude: "6.8",
    distance: "18 300 al",
  },
  {
    id: "m29",
    name: "M29",
    type: "Amas ouvert",
    done: false,
    constellation: "Cygne",
    magnitude: "7.1",
    distance: "4 000 al",
  },
  {
    id: "m30",
    name: "M30",
    type: "Amas globulaire",
    done: false,
    constellation: "Capricorne",
    magnitude: "7.2",
    distance: "28 000 al",
  },
  {
    id: "m31",
    name: "M31 — Galaxie d'Andromede",
    type: "Galaxie spirale",
    done: false,
    constellation: "Andromede",
    magnitude: "3.4",
    distance: "2,537 Mal",
  },
  {
    id: "m32",
    name: "M32",
    type: "Galaxie elliptique",
    done: false,
    constellation: "Andromede",
    magnitude: "8.7",
    distance: "2,490 Mal",
  },
  {
    id: "m33",
    name: "M33 — Galaxie du Triangle",
    type: "Galaxie spirale",
    done: false,
    constellation: "Triangle",
    magnitude: "5.7",
    distance: "2,730 Mal",
  },
  {
    id: "m34",
    name: "M34",
    type: "Amas ouvert",
    done: false,
    constellation: "Persee",
    magnitude: "5.2",
    distance: "1 400 al",
  },
  {
    id: "m35",
    name: "M35",
    type: "Amas ouvert",
    done: false,
    constellation: "Gemeaux",
    magnitude: "5.1",
    distance: "2 800 al",
  },
  {
    id: "m36",
    name: "M36",
    type: "Amas ouvert",
    done: false,
    constellation: "Cocher",
    magnitude: "6.0",
    distance: "4 100 al",
  },
  {
    id: "m37",
    name: "M37",
    type: "Amas ouvert",
    done: false,
    constellation: "Cocher",
    magnitude: "5.6",
    distance: "4 400 al",
  },
  {
    id: "m38",
    name: "M38",
    type: "Amas ouvert",
    done: false,
    constellation: "Cocher",
    magnitude: "6.4",
    distance: "4 200 al",
  },
  {
    id: "m39",
    name: "M39",
    type: "Amas ouvert",
    done: false,
    constellation: "Cygne",
    magnitude: "4.6",
    distance: "825 al",
  },
  {
    id: "m40",
    name: "M40 — Winnecke 4",
    type: "Etoile double",
    done: false,
    constellation: "Grande Ourse",
    magnitude: "8.4",
    distance: "510 al",
  },
  {
    id: "m41",
    name: "M41",
    type: "Amas ouvert",
    done: false,
    constellation: "Grand Chien",
    magnitude: "4.5",
    distance: "2 300 al",
  },
  {
    id: "m42",
    name: "M42 — Nebuleuse d'Orion",
    type: "Nebuleuse en emission",
    done: false,
    constellation: "Orion",
    magnitude: "4.0",
    distance: "1 344 al",
  },
  {
    id: "m43",
    name: "M43 — Nebuleuse De Mairan",
    type: "Nebuleuse en emission",
    done: false,
    constellation: "Orion",
    magnitude: "9.0",
    distance: "1 600 al",
  },
  {
    id: "m44",
    name: "M44 — La Ruche",
    type: "Amas ouvert",
    done: false,
    constellation: "Cancer",
    magnitude: "3.1",
    distance: "577 al",
  },
  {
    id: "m45",
    name: "M45 — Pleiades",
    type: "Amas ouvert",
    done: false,
    constellation: "Taureau",
    magnitude: "1.6",
    distance: "444 al",
  },
  {
    id: "m46",
    name: "M46",
    type: "Amas ouvert",
    done: false,
    constellation: "Poupe",
    magnitude: "6.1",
    distance: "5 400 al",
  },
  {
    id: "m47",
    name: "M47",
    type: "Amas ouvert",
    done: false,
    constellation: "Poupe",
    magnitude: "4.4",
    distance: "1 600 al",
  },
  {
    id: "m48",
    name: "M48",
    type: "Amas ouvert",
    done: false,
    constellation: "Hydre femelle",
    magnitude: "5.8",
    distance: "1 500 al",
  },
  {
    id: "m49",
    name: "M49",
    type: "Galaxie elliptique",
    done: false,
    constellation: "Vierge",
    magnitude: "8.4",
    distance: "56 Mal",
  },
  {
    id: "m50",
    name: "M50",
    type: "Amas ouvert",
    done: false,
    constellation: "Licorne",
    magnitude: "5.9",
    distance: "3 200 al",
  },
  {
    id: "m51",
    name: "M51 — Galaxie du Tourbillon",
    type: "Galaxie spirale",
    done: false,
    constellation: "Chiens de chasse",
    magnitude: "8.4",
    distance: "23 Mal",
  },
  {
    id: "m52",
    name: "M52",
    type: "Amas ouvert",
    done: false,
    constellation: "Cassiopee",
    magnitude: "5.0",
    distance: "5 000 al",
  },
  {
    id: "m53",
    name: "M53",
    type: "Amas globulaire",
    done: false,
    constellation: "Cheveture de Berenice",
    magnitude: "7.6",
    distance: "58 000 al",
  },
  {
    id: "m54",
    name: "M54",
    type: "Amas globulaire",
    done: false,
    constellation: "Sagittaire",
    magnitude: "7.6",
    distance: "87 400 al",
  },
  {
    id: "m55",
    name: "M55",
    type: "Amas globulaire",
    done: false,
    constellation: "Sagittaire",
    magnitude: "6.3",
    distance: "17 600 al",
  },
  {
    id: "m56",
    name: "M56",
    type: "Amas globulaire",
    done: false,
    constellation: "Lyre",
    magnitude: "8.3",
    distance: "32 900 al",
  },
  {
    id: "m57",
    name: "M57 — Anneau de la Lyre",
    type: "Nebuleuse planetaire",
    done: false,
    constellation: "Lyre",
    magnitude: "8.8",
    distance: "2 300 al",
  },
  {
    id: "m58",
    name: "M58",
    type: "Galaxie spirale barree",
    done: false,
    constellation: "Vierge",
    magnitude: "9.7",
    distance: "62 Mal",
  },
  {
    id: "m59",
    name: "M59",
    type: "Galaxie elliptique",
    done: false,
    constellation: "Vierge",
    magnitude: "9.6",
    distance: "60 Mal",
  },
  {
    id: "m60",
    name: "M60",
    type: "Galaxie elliptique",
    done: false,
    constellation: "Vierge",
    magnitude: "8.8",
    distance: "55 Mal",
  },
  {
    id: "m61",
    name: "M61",
    type: "Galaxie spirale barree",
    done: false,
    constellation: "Vierge",
    magnitude: "9.7",
    distance: "52 Mal",
  },
  {
    id: "m62",
    name: "M62",
    type: "Amas globulaire",
    done: false,
    constellation: "Ophiuchus",
    magnitude: "6.5",
    distance: "22 500 al",
  },
  {
    id: "m63",
    name: "M63 — Galaxie du Tournesol",
    type: "Galaxie spirale",
    done: false,
    constellation: "Chiens de chasse",
    magnitude: "8.6",
    distance: "37 Mal",
  },
  {
    id: "m64",
    name: "M64 — Galaxie Oeil Noir",
    type: "Galaxie spirale",
    done: false,
    constellation: "Cheveture de Berenice",
    magnitude: "8.5",
    distance: "17 Mal",
  },
  {
    id: "m65",
    name: "M65",
    type: "Galaxie spirale",
    done: false,
    constellation: "Lion",
    magnitude: "9.3",
    distance: "35 Mal",
  },
  {
    id: "m66",
    name: "M66",
    type: "Galaxie spirale barree",
    done: false,
    constellation: "Lion",
    magnitude: "8.9",
    distance: "36 Mal",
  },
  {
    id: "m67",
    name: "M67",
    type: "Amas ouvert",
    done: false,
    constellation: "Cancer",
    magnitude: "6.1",
    distance: "2 700 al",
  },
  {
    id: "m68",
    name: "M68",
    type: "Amas globulaire",
    done: false,
    constellation: "Hydre femelle",
    magnitude: "7.8",
    distance: "33 600 al",
  },
  {
    id: "m69",
    name: "M69",
    type: "Amas globulaire",
    done: false,
    constellation: "Sagittaire",
    magnitude: "7.6",
    distance: "29 700 al",
  },
  {
    id: "m70",
    name: "M70",
    type: "Amas globulaire",
    done: false,
    constellation: "Sagittaire",
    magnitude: "7.9",
    distance: "29 400 al",
  },
  {
    id: "m71",
    name: "M71",
    type: "Amas globulaire",
    done: false,
    constellation: "Fleche",
    magnitude: "6.1",
    distance: "12 000 al",
  },
  {
    id: "m72",
    name: "M72",
    type: "Amas globulaire",
    done: false,
    constellation: "Verseau",
    magnitude: "9.3",
    distance: "55 400 al",
  },
  {
    id: "m73",
    name: "M73",
    type: "Asterisme",
    done: false,
    constellation: "Verseau",
    magnitude: "9.0",
    distance: "2 000 al",
  },
  {
    id: "m74",
    name: "M74",
    type: "Galaxie spirale",
    done: false,
    constellation: "Poissons",
    magnitude: "9.4",
    distance: "32 Mal",
  },
  {
    id: "m75",
    name: "M75",
    type: "Amas globulaire",
    done: false,
    constellation: "Sagittaire",
    magnitude: "8.5",
    distance: "67 500 al",
  },
  {
    id: "m76",
    name: "M76 — Petite Nebuleuse Haltere",
    type: "Nebuleuse planetaire",
    done: false,
    constellation: "Persee",
    magnitude: "10.1",
    distance: "2 500 al",
  },
  {
    id: "m77",
    name: "M77",
    type: "Galaxie spirale barree",
    done: false,
    constellation: "Baleine",
    magnitude: "8.9",
    distance: "47 Mal",
  },
  {
    id: "m78",
    name: "M78",
    type: "Nebuleuse par reflexion",
    done: false,
    constellation: "Orion",
    magnitude: "8.3",
    distance: "1 600 al",
  },
  {
    id: "m79",
    name: "M79",
    type: "Amas globulaire",
    done: false,
    constellation: "Lievre",
    magnitude: "7.7",
    distance: "41 000 al",
  },
  {
    id: "m80",
    name: "M80",
    type: "Amas globulaire",
    done: false,
    constellation: "Scorpion",
    magnitude: "7.3",
    distance: "32 600 al",
  },
  {
    id: "m81",
    name: "M81 — Galaxie de Bode",
    type: "Galaxie spirale",
    done: false,
    constellation: "Grande Ourse",
    magnitude: "6.9",
    distance: "11,8 Mal",
  },
  {
    id: "m82",
    name: "M82 — Galaxie du Cigare",
    type: "Galaxie irreguliere",
    done: false,
    constellation: "Grande Ourse",
    magnitude: "8.4",
    distance: "11,5 Mal",
  },
  {
    id: "m83",
    name: "M83 — Galaxie du Moulinet",
    type: "Galaxie spirale barree",
    done: false,
    constellation: "Hydre femelle",
    magnitude: "7.5",
    distance: "14,7 Mal",
  },
  {
    id: "m84",
    name: "M84",
    type: "Galaxie lenticulaire",
    done: false,
    constellation: "Vierge",
    magnitude: "9.1",
    distance: "60 Mal",
  },
  {
    id: "m85",
    name: "M85",
    type: "Galaxie lenticulaire",
    done: false,
    constellation: "Cheveture de Berenice",
    magnitude: "9.1",
    distance: "60 Mal",
  },
  {
    id: "m86",
    name: "M86",
    type: "Galaxie lenticulaire",
    done: false,
    constellation: "Vierge",
    magnitude: "8.9",
    distance: "52 Mal",
  },
  {
    id: "m87",
    name: "M87 — Virgo A",
    type: "Galaxie elliptique",
    done: false,
    constellation: "Vierge",
    magnitude: "8.6",
    distance: "53,5 Mal",
  },
  {
    id: "m88",
    name: "M88",
    type: "Galaxie spirale",
    done: false,
    constellation: "Cheveture de Berenice",
    magnitude: "9.6",
    distance: "60 Mal",
  },
  {
    id: "m89",
    name: "M89",
    type: "Galaxie elliptique",
    done: false,
    constellation: "Vierge",
    magnitude: "9.8",
    distance: "58 Mal",
  },
  {
    id: "m90",
    name: "M90",
    type: "Galaxie lenticulaire",
    done: false,
    constellation: "Vierge",
    magnitude: "9.5",
    distance: "58 Mal",
  },
  {
    id: "m91",
    name: "M91",
    type: "Galaxie spirale barree",
    done: false,
    constellation: "Cheveture de Berenice",
    magnitude: "10.2",
    distance: "63 Mal",
  },
  {
    id: "m92",
    name: "M92",
    type: "Amas globulaire",
    done: false,
    constellation: "Hercule",
    magnitude: "6.4",
    distance: "26 700 al",
  },
  {
    id: "m93",
    name: "M93",
    type: "Amas ouvert",
    done: false,
    constellation: "Poupe",
    magnitude: "6.2",
    distance: "3 600 al",
  },
  {
    id: "m94",
    name: "M94",
    type: "Galaxie spirale",
    done: false,
    constellation: "Chiens de chasse",
    magnitude: "8.2",
    distance: "16 Mal",
  },
  {
    id: "m95",
    name: "M95",
    type: "Galaxie spirale barree",
    done: false,
    constellation: "Lion",
    magnitude: "9.7",
    distance: "38 Mal",
  },
  {
    id: "m96",
    name: "M96",
    type: "Galaxie spirale",
    done: false,
    constellation: "Lion",
    magnitude: "9.2",
    distance: "38 Mal",
  },
  {
    id: "m97",
    name: "M97 — Nebuleuse du Hibou",
    type: "Nebuleuse planetaire",
    done: false,
    constellation: "Grande Ourse",
    magnitude: "9.9",
    distance: "2 030 al",
  },
  {
    id: "m98",
    name: "M98",
    type: "Galaxie spirale",
    done: false,
    constellation: "Cheveture de Berenice",
    magnitude: "10.1",
    distance: "44 Mal",
  },
  {
    id: "m99",
    name: "M99",
    type: "Galaxie spirale",
    done: false,
    constellation: "Cheveture de Berenice",
    magnitude: "9.9",
    distance: "49 Mal",
  },
  {
    id: "m100",
    name: "M100",
    type: "Galaxie spirale barree",
    done: false,
    constellation: "Cheveture de Berenice",
    magnitude: "9.3",
    distance: "55 Mal",
  },
  {
    id: "m101",
    name: "M101 — Galaxie du Moulinet",
    type: "Galaxie spirale",
    done: false,
    constellation: "Grande Ourse",
    magnitude: "7.9",
    distance: "20,9 Mal",
  },
  {
    id: "m102",
    name: "M102 — Galaxie du Fuseau",
    type: "Galaxie lenticulaire",
    done: false,
    constellation: "Dragon",
    magnitude: "9.9",
    distance: "44 Mal",
  },
  {
    id: "m103",
    name: "M103",
    type: "Amas ouvert",
    done: false,
    constellation: "Cassiopee",
    magnitude: "7.4",
    distance: "8 500 al",
  },
  {
    id: "m104",
    name: "M104 — Galaxie Sombrero",
    type: "Galaxie spirale",
    done: false,
    constellation: "Vierge",
    magnitude: "8.0",
    distance: "29,3 Mal",
  },
  {
    id: "m105",
    name: "M105",
    type: "Galaxie elliptique",
    done: false,
    constellation: "Lion",
    magnitude: "9.8",
    distance: "38 Mal",
  },
  {
    id: "m106",
    name: "M106",
    type: "Galaxie spirale",
    done: false,
    constellation: "Chiens de chasse",
    magnitude: "8.4",
    distance: "22,8 Mal",
  },
  {
    id: "m107",
    name: "M107",
    type: "Amas globulaire",
    done: false,
    constellation: "Ophiuchus",
    magnitude: "7.9",
    distance: "20 900 al",
  },
  {
    id: "m108",
    name: "M108",
    type: "Galaxie spirale barree",
    done: false,
    constellation: "Grande Ourse",
    magnitude: "10.0",
    distance: "45 Mal",
  },
  {
    id: "m109",
    name: "M109",
    type: "Galaxie spirale barree",
    done: false,
    constellation: "Grande Ourse",
    magnitude: "9.8",
    distance: "83,5 Mal",
  },
  {
    id: "m110",
    name: "M110",
    type: "Galaxie elliptique naine",
    done: false,
    constellation: "Andromede",
    magnitude: "8.5",
    distance: "2,69 Mal",
  },
];

const DEFAULT_DATA: Domain[] = [
  {
    id: "astro",
    label: "Astronomie",
    icon: "🔭",
    color: "#1D9E75",
    objects: MESSIER,
  },
  {
    id: "fleurs",
    label: "Fleurs",
    icon: "🌸",
    color: "#D4537E",
    objects: [
      {
        id: "f01",
        name: "Coquelicot",
        type: "Fleur sauvage",
        done: false,
        constellation: "Papaveraceae",
        magnitude: "Mai-juillet",
        distance: "Champs, bords de route",
      },
      {
        id: "f02",
        name: "Bleuet des champs",
        type: "Fleur sauvage",
        done: false,
        constellation: "Asteraceae",
        magnitude: "Juin-aout",
        distance: "Champs de cereales",
      },
      {
        id: "f03",
        name: "Marguerite commune",
        type: "Fleur sauvage",
        done: false,
        constellation: "Asteraceae",
        magnitude: "Mai-aout",
        distance: "Prairies, talus",
      },
      {
        id: "f04",
        name: "Bouton d'or",
        type: "Fleur sauvage",
        done: false,
        constellation: "Ranunculaceae",
        magnitude: "Avril-juillet",
        distance: "Prairies humides",
      },
      {
        id: "f05",
        name: "Pissenlit",
        type: "Fleur sauvage",
        done: false,
        constellation: "Asteraceae",
        magnitude: "Mars-mai",
        distance: "Partout",
      },
      {
        id: "f06",
        name: "Caille-lait blanc",
        type: "Fleur sauvage",
        done: false,
        constellation: "Rubiaceae",
        magnitude: "Juin-aout",
        distance: "Haies, lisières",
      },
      {
        id: "f07",
        name: "Achillee millefeuille",
        type: "Fleur sauvage",
        done: false,
        constellation: "Asteraceae",
        magnitude: "Juin-aout",
        distance: "Prairies, chemins",
      },
      {
        id: "f08",
        name: "Centauree jacee",
        type: "Fleur sauvage",
        done: false,
        constellation: "Asteraceae",
        magnitude: "Juin-octobre",
        distance: "Prairies seches",
      },
      {
        id: "f09",
        name: "Epilobe en epi",
        type: "Fleur sauvage",
        done: false,
        constellation: "Onagraceae",
        magnitude: "Juillet-aout",
        distance: "Coupes forestieres",
      },
      {
        id: "f10",
        name: "Grande digitale",
        type: "Fleur sauvage",
        done: false,
        constellation: "Plantaginaceae",
        magnitude: "Juin-aout",
        distance: "Lisières, landes",
      },
      {
        id: "f11",
        name: "Scabieuse des champs",
        type: "Fleur sauvage",
        done: false,
        constellation: "Caprifoliaceae",
        magnitude: "Juillet-aout",
        distance: "Prairies calcaires",
      },
      {
        id: "f12",
        name: "Lierre terrestre",
        type: "Fleur sauvage",
        done: false,
        constellation: "Lamiaceae",
        magnitude: "Mars-mai",
        distance: "Haies, jardins",
      },
      {
        id: "f13",
        name: "Liseron des champs",
        type: "Fleur sauvage",
        done: false,
        constellation: "Convolvulaceae",
        magnitude: "Juin-septembre",
        distance: "Champs, chemins",
      },
      {
        id: "f14",
        name: "Millepertuis perfore",
        type: "Fleur sauvage",
        done: false,
        constellation: "Hypericaceae",
        magnitude: "Juin-septembre",
        distance: "Prairies, talus",
      },
      {
        id: "f15",
        name: "Nenuphare blanc",
        type: "Fleur aquatique",
        done: false,
        constellation: "Nymphaeaceae",
        magnitude: "Juin-aout",
        distance: "Etangs, rivieres lentes",
      },
      {
        id: "f16",
        name: "Iris des marais",
        type: "Fleur aquatique",
        done: false,
        constellation: "Iridaceae",
        magnitude: "Mai-juillet",
        distance: "Berges, marais",
      },
      {
        id: "f17",
        name: "Jonquille",
        type: "Fleur sauvage",
        done: false,
        constellation: "Amaryllidaceae",
        magnitude: "Mars-avril",
        distance: "Prairies, sous-bois",
      },
      {
        id: "f18",
        name: "Violette odorante",
        type: "Fleur sauvage",
        done: false,
        constellation: "Violaceae",
        magnitude: "Mars-avril",
        distance: "Haies, jardins",
      },
      {
        id: "f19",
        name: "Primevere officinale",
        type: "Fleur sauvage",
        done: false,
        constellation: "Primulaceae",
        magnitude: "Mars-mai",
        distance: "Prairies, bois clairs",
      },
      {
        id: "f20",
        name: "Ancolie commune",
        type: "Fleur sauvage",
        done: false,
        constellation: "Ranunculaceae",
        magnitude: "Mai-juillet",
        distance: "Sous-bois, rochers",
      },
      {
        id: "f21",
        name: "Lavande vraie",
        type: "Plante aromatique",
        done: false,
        constellation: "Lamiaceae",
        magnitude: "Juin-aout",
        distance: "Garrigues, maquis",
      },
      {
        id: "f22",
        name: "Romarin",
        type: "Plante aromatique",
        done: false,
        constellation: "Lamiaceae",
        magnitude: "Fevrier-mai",
        distance: "Garrigues mediterraneennes",
      },
      {
        id: "f23",
        name: "Thym serpolet",
        type: "Plante aromatique",
        done: false,
        constellation: "Lamiaceae",
        magnitude: "Mai-aout",
        distance: "Pelouses seches, rochers",
      },
      {
        id: "f24",
        name: "Sauge des pres",
        type: "Plante aromatique",
        done: false,
        constellation: "Lamiaceae",
        magnitude: "Mai-juillet",
        distance: "Prairies, talus",
      },
      {
        id: "f25",
        name: "Tournesol",
        type: "Fleur cultivee",
        done: false,
        constellation: "Asteraceae",
        magnitude: "Juillet-aout",
        distance: "Champs cultives",
      },
      {
        id: "f26",
        name: "Rose trefle",
        type: "Fleur cultivee",
        done: false,
        constellation: "Fabaceae",
        magnitude: "Mai-septembre",
        distance: "Prairies, jardins",
      },
      {
        id: "f27",
        name: "Dahlia",
        type: "Fleur cultivee",
        done: false,
        constellation: "Asteraceae",
        magnitude: "Juillet-octobre",
        distance: "Jardins",
      },
      {
        id: "f28",
        name: "Genet a balais",
        type: "Arbuste",
        done: false,
        constellation: "Fabaceae",
        magnitude: "Avril-juin",
        distance: "Landes, coupes forestieres",
      },
      {
        id: "f29",
        name: "Ajonc d'Europe",
        type: "Arbuste",
        done: false,
        constellation: "Fabaceae",
        magnitude: "Janvier-mai",
        distance: "Landes, cotes atlantiques",
      },
      {
        id: "f30",
        name: "Bruyere cendree",
        type: "Arbuste",
        done: false,
        constellation: "Ericaceae",
        magnitude: "Juillet-aout",
        distance: "Landes, tourbières",
      },
      {
        id: "f31",
        name: "Digitale pourpre",
        type: "Fleur sauvage",
        done: false,
        constellation: "Plantaginaceae",
        magnitude: "Juin-aout",
        distance: "Lisières, landes",
      },
      {
        id: "f32",
        name: "Grande ortie",
        type: "Plante commune",
        done: false,
        constellation: "Urticaceae",
        magnitude: "Juin-septembre",
        distance: "Partout",
      },
      {
        id: "f33",
        name: "Gaillet gratteron",
        type: "Plante commune",
        done: false,
        constellation: "Rubiaceae",
        magnitude: "Mai-juillet",
        distance: "Haies, jardins",
      },
      {
        id: "f34",
        name: "Chardon aux anes",
        type: "Fleur sauvage",
        done: false,
        constellation: "Asteraceae",
        magnitude: "Juillet-aout",
        distance: "Chemins, friches",
      },
      {
        id: "f35",
        name: "Cardamine des pres",
        type: "Fleur sauvage",
        done: false,
        constellation: "Brassicaceae",
        magnitude: "Avril-juin",
        distance: "Prairies humides",
      },
      {
        id: "f36",
        name: "Renoncule acre",
        type: "Fleur sauvage",
        done: false,
        constellation: "Ranunculaceae",
        magnitude: "Avril-juillet",
        distance: "Prairies, jardins",
      },
      {
        id: "f37",
        name: "Oxalide petite oseille",
        type: "Fleur sauvage",
        done: false,
        constellation: "Oxalidaceae",
        magnitude: "Avril-octobre",
        distance: "Jardins, chemins",
      },
      {
        id: "f38",
        name: "Geranium herbe a robert",
        type: "Fleur sauvage",
        done: false,
        constellation: "Geraniaceae",
        magnitude: "Mai-septembre",
        distance: "Haies, murs",
      },
      {
        id: "f39",
        name: "Stellaire holostee",
        type: "Fleur sauvage",
        done: false,
        constellation: "Caryophyllaceae",
        magnitude: "Avril-juin",
        distance: "Haies, sous-bois",
      },
      {
        id: "f40",
        name: "Veronique de Perse",
        type: "Fleur sauvage",
        done: false,
        constellation: "Plantaginaceae",
        magnitude: "Mars-octobre",
        distance: "Jardins, chemins",
      },
    ],
  },
  {
    id: "arbres",
    label: "Arbres",
    icon: "🌲",
    color: "#639922",
    objects: [
      {
        id: "a01",
        name: "Chene pedoncule",
        type: "Feuillu",
        done: false,
        constellation: "Fagaceae",
        magnitude: "Caduc",
        distance: "Plaines, vallees",
      },
      {
        id: "a02",
        name: "Chene sessile",
        type: "Feuillu",
        done: false,
        constellation: "Fagaceae",
        magnitude: "Caduc",
        distance: "Collines, massifs",
      },
      {
        id: "a03",
        name: "Hetre commun",
        type: "Feuillu",
        done: false,
        constellation: "Fagaceae",
        magnitude: "Caduc",
        distance: "Forets de montagne",
      },
      {
        id: "a04",
        name: "Charme commun",
        type: "Feuillu",
        done: false,
        constellation: "Betulaceae",
        magnitude: "Caduc",
        distance: "Forets mixtes",
      },
      {
        id: "a05",
        name: "Chataignier",
        type: "Feuillu",
        done: false,
        constellation: "Fagaceae",
        magnitude: "Caduc",
        distance: "Sols siliceux",
      },
      {
        id: "a06",
        name: "Frene commun",
        type: "Feuillu",
        done: false,
        constellation: "Oleaceae",
        magnitude: "Caduc",
        distance: "Vallees humides",
      },
      {
        id: "a07",
        name: "Erable sycomore",
        type: "Feuillu",
        done: false,
        constellation: "Sapindaceae",
        magnitude: "Caduc",
        distance: "Forets mixtes",
      },
      {
        id: "a08",
        name: "Erable champetre",
        type: "Feuillu",
        done: false,
        constellation: "Sapindaceae",
        magnitude: "Caduc",
        distance: "Haies, lisières",
      },
      {
        id: "a09",
        name: "Tilleul a grandes feuilles",
        type: "Feuillu",
        done: false,
        constellation: "Malvaceae",
        magnitude: "Caduc",
        distance: "Forets, parcs",
      },
      {
        id: "a10",
        name: "Tilleul a petites feuilles",
        type: "Feuillu",
        done: false,
        constellation: "Malvaceae",
        magnitude: "Caduc",
        distance: "Forets calcaires",
      },
      {
        id: "a11",
        name: "Bouleau verruqueux",
        type: "Feuillu",
        done: false,
        constellation: "Betulaceae",
        magnitude: "Caduc",
        distance: "Landes, tourbieres",
      },
      {
        id: "a12",
        name: "Aulne glutineux",
        type: "Feuillu",
        done: false,
        constellation: "Betulaceae",
        magnitude: "Caduc",
        distance: "Berges, zones humides",
      },
      {
        id: "a13",
        name: "Tremble",
        type: "Feuillu",
        done: false,
        constellation: "Salicaceae",
        magnitude: "Caduc",
        distance: "Coupes, lisières",
      },
      {
        id: "a14",
        name: "Peuplier noir",
        type: "Feuillu",
        done: false,
        constellation: "Salicaceae",
        magnitude: "Caduc",
        distance: "Berges, plaines",
      },
      {
        id: "a15",
        name: "Saule blanc",
        type: "Feuillu",
        done: false,
        constellation: "Salicaceae",
        magnitude: "Caduc",
        distance: "Berges de rivieres",
      },
      {
        id: "a16",
        name: "Saule pleureur",
        type: "Feuillu",
        done: false,
        constellation: "Salicaceae",
        magnitude: "Caduc",
        distance: "Parcs, berges",
      },
      {
        id: "a17",
        name: "Merisier",
        type: "Feuillu",
        done: false,
        constellation: "Rosaceae",
        magnitude: "Caduc",
        distance: "Forets, haies",
      },
      {
        id: "a18",
        name: "Pommier sauvage",
        type: "Feuillu",
        done: false,
        constellation: "Rosaceae",
        magnitude: "Caduc",
        distance: "Haies, lisières",
      },
      {
        id: "a19",
        name: "Poirier sauvage",
        type: "Feuillu",
        done: false,
        constellation: "Rosaceae",
        magnitude: "Caduc",
        distance: "Forets claires, haies",
      },
      {
        id: "a20",
        name: "Sorbier des oiseleurs",
        type: "Feuillu",
        done: false,
        constellation: "Rosaceae",
        magnitude: "Caduc",
        distance: "Montagne, lisières",
      },
      {
        id: "a21",
        name: "Alisier torminal",
        type: "Feuillu",
        done: false,
        constellation: "Rosaceae",
        magnitude: "Caduc",
        distance: "Forets calcaires",
      },
      {
        id: "a22",
        name: "Noyer commun",
        type: "Feuillu",
        done: false,
        constellation: "Juglandaceae",
        magnitude: "Caduc",
        distance: "Campagnes, jardins",
      },
      {
        id: "a23",
        name: "Robinier faux-acacia",
        type: "Feuillu",
        done: false,
        constellation: "Fabaceae",
        magnitude: "Caduc",
        distance: "Friches, bords de route",
      },
      {
        id: "a24",
        name: "Platane commun",
        type: "Feuillu",
        done: false,
        constellation: "Platanaceae",
        magnitude: "Caduc",
        distance: "Villes, bords de route",
      },
      {
        id: "a25",
        name: "Marronnier d'Inde",
        type: "Feuillu",
        done: false,
        constellation: "Sapindaceae",
        magnitude: "Caduc",
        distance: "Parcs, avenues",
      },
      {
        id: "a26",
        name: "Pin sylvestre",
        type: "Conifere",
        done: false,
        constellation: "Pinaceae",
        magnitude: "Persistant",
        distance: "Landes, montagne",
      },
      {
        id: "a27",
        name: "Pin maritime",
        type: "Conifere",
        done: false,
        constellation: "Pinaceae",
        magnitude: "Persistant",
        distance: "Cotes atlantiques",
      },
      {
        id: "a28",
        name: "Pin laricio",
        type: "Conifere",
        done: false,
        constellation: "Pinaceae",
        magnitude: "Persistant",
        distance: "Montagne, Corse",
      },
      {
        id: "a29",
        name: "Epicea commun",
        type: "Conifere",
        done: false,
        constellation: "Pinaceae",
        magnitude: "Persistant",
        distance: "Montagne, forets boreales",
      },
      {
        id: "a30",
        name: "Sapin pectine",
        type: "Conifere",
        done: false,
        constellation: "Pinaceae",
        magnitude: "Persistant",
        distance: "Montagne, Vosges, Alpes",
      },
      {
        id: "a31",
        name: "Douglas vert",
        type: "Conifere",
        done: false,
        constellation: "Pinaceae",
        magnitude: "Persistant",
        distance: "Forets de reboisement",
      },
      {
        id: "a32",
        name: "Meleze d'Europe",
        type: "Conifere",
        done: false,
        constellation: "Pinaceae",
        magnitude: "Caduc",
        distance: "Alpes, hautes vallees",
      },
      {
        id: "a33",
        name: "Cedre de l'Atlas",
        type: "Conifere",
        done: false,
        constellation: "Pinaceae",
        magnitude: "Persistant",
        distance: "Parcs, forets du Sud",
      },
      {
        id: "a34",
        name: "If commun",
        type: "Conifere",
        done: false,
        constellation: "Taxaceae",
        magnitude: "Persistant",
        distance: "Sous-bois, cimetières",
      },
      {
        id: "a35",
        name: "Thuya geant",
        type: "Conifere",
        done: false,
        constellation: "Cupressaceae",
        magnitude: "Persistant",
        distance: "Parcs, haies",
      },
      {
        id: "a36",
        name: "Cypres de Provence",
        type: "Conifere",
        done: false,
        constellation: "Cupressaceae",
        magnitude: "Persistant",
        distance: "Mediterranee",
      },
      {
        id: "a37",
        name: "Genevrier commun",
        type: "Conifere",
        done: false,
        constellation: "Cupressaceae",
        magnitude: "Persistant",
        distance: "Landes, pelouses calcaires",
      },
      {
        id: "a38",
        name: "Orme champetre",
        type: "Feuillu",
        done: false,
        constellation: "Ulmaceae",
        magnitude: "Caduc",
        distance: "Haies, forets alluviales",
      },
      {
        id: "a39",
        name: "Micocoulier de Provence",
        type: "Feuillu",
        done: false,
        constellation: "Cannabaceae",
        magnitude: "Caduc",
        distance: "Sud de la France",
      },
      {
        id: "a40",
        name: "Chene vert",
        type: "Feuillu persistant",
        done: false,
        constellation: "Fagaceae",
        magnitude: "Persistant",
        distance: "Garrigue, Mediterranee",
      },
    ],
  },
  {
    id: "oiseaux",
    label: "Oiseaux",
    icon: "🦅",
    color: "#378ADD",
    objects: [
      {
        id: "o01",
        name: "Moineau domestique",
        type: "Passereau",
        done: false,
        constellation: "Passeridae",
        magnitude: "22-25 cm",
        distance: "Villes, villages",
      },
      {
        id: "o02",
        name: "Merle noir",
        type: "Passereau",
        done: false,
        constellation: "Turdidae",
        magnitude: "24-25 cm",
        distance: "Jardins, forets",
      },
      {
        id: "o03",
        name: "Rouge-gorge familier",
        type: "Passereau",
        done: false,
        constellation: "Muscicapidae",
        magnitude: "14 cm",
        distance: "Jardins, sous-bois",
      },
      {
        id: "o04",
        name: "Mesange charbonniere",
        type: "Passereau",
        done: false,
        constellation: "Paridae",
        magnitude: "14 cm",
        distance: "Forets, jardins",
      },
      {
        id: "o05",
        name: "Mesange bleue",
        type: "Passereau",
        done: false,
        constellation: "Paridae",
        magnitude: "12 cm",
        distance: "Forets, jardins",
      },
      {
        id: "o06",
        name: "Mesange longue queue",
        type: "Passereau",
        done: false,
        constellation: "Aegithalidae",
        magnitude: "14 cm",
        distance: "Haies, forets",
      },
      {
        id: "o07",
        name: "Pinson des arbres",
        type: "Passereau",
        done: false,
        constellation: "Fringillidae",
        magnitude: "14-16 cm",
        distance: "Forets, jardins",
      },
      {
        id: "o08",
        name: "Pinson du Nord",
        type: "Passereau",
        done: false,
        constellation: "Fringillidae",
        magnitude: "15-18 cm",
        distance: "Forets, campagnes",
      },
      {
        id: "o09",
        name: "Verdier d'Europe",
        type: "Passereau",
        done: false,
        constellation: "Fringillidae",
        magnitude: "15 cm",
        distance: "Jardins, haies",
      },
      {
        id: "o10",
        name: "Chardonneret elegant",
        type: "Passereau",
        done: false,
        constellation: "Fringillidae",
        magnitude: "12-13 cm",
        distance: "Jardins, friches",
      },
      {
        id: "o11",
        name: "Bouvreuil pivoine",
        type: "Passereau",
        done: false,
        constellation: "Fringillidae",
        magnitude: "14-16 cm",
        distance: "Forets, jardins",
      },
      {
        id: "o12",
        name: "Grosbec casse-noyaux",
        type: "Passereau",
        done: false,
        constellation: "Fringillidae",
        magnitude: "16-18 cm",
        distance: "Forets de feuillus",
      },
      {
        id: "o13",
        name: "Linotte melodieuse",
        type: "Passereau",
        done: false,
        constellation: "Fringillidae",
        magnitude: "13-14 cm",
        distance: "Landes, bocages",
      },
      {
        id: "o14",
        name: "Etourneau sansonnet",
        type: "Passereau",
        done: false,
        constellation: "Sturnidae",
        magnitude: "21 cm",
        distance: "Villes, campagnes",
      },
      {
        id: "o15",
        name: "Hirondelle de cheminee",
        type: "Passereau",
        done: false,
        constellation: "Hirundinidae",
        magnitude: "17-21 cm",
        distance: "Campagnes, fermes",
      },
      {
        id: "o16",
        name: "Hirondelle de fenetre",
        type: "Passereau",
        done: false,
        constellation: "Hirundinidae",
        magnitude: "13-15 cm",
        distance: "Villes, villages",
      },
      {
        id: "o17",
        name: "Martinet noir",
        type: "Apodiforme",
        done: false,
        constellation: "Apodidae",
        magnitude: "40-44 cm",
        distance: "Villes, falaises",
      },
      {
        id: "o18",
        name: "Bergeronnette grise",
        type: "Passereau",
        done: false,
        constellation: "Motacillidae",
        magnitude: "28 cm",
        distance: "Villes, berges",
      },
      {
        id: "o19",
        name: "Bergeronnette printaniere",
        type: "Passereau",
        done: false,
        constellation: "Motacillidae",
        magnitude: "28 cm",
        distance: "Prairies humides",
      },
      {
        id: "o20",
        name: "Grive musicienne",
        type: "Passereau",
        done: false,
        constellation: "Turdidae",
        magnitude: "23 cm",
        distance: "Forets, jardins",
      },
      {
        id: "o21",
        name: "Grive litorne",
        type: "Passereau",
        done: false,
        constellation: "Turdidae",
        magnitude: "25-28 cm",
        distance: "Campagnes, parcs",
      },
      {
        id: "o22",
        name: "Troglodyte mignon",
        type: "Passereau",
        done: false,
        constellation: "Troglodytidae",
        magnitude: "9-10 cm",
        distance: "Sous-bois, jardins",
      },
      {
        id: "o23",
        name: "Fauvette a tete noire",
        type: "Passereau",
        done: false,
        constellation: "Sylviidae",
        magnitude: "13-15 cm",
        distance: "Haies, jardins",
      },
      {
        id: "o24",
        name: "Pouillot veloce",
        type: "Passereau",
        done: false,
        constellation: "Phylloscopidae",
        magnitude: "10-12 cm",
        distance: "Forets, jardins",
      },
      {
        id: "o25",
        name: "Roitelet huppe",
        type: "Passereau",
        done: false,
        constellation: "Regulidae",
        magnitude: "14-15 cm",
        distance: "Coniferes, forets",
      },
      {
        id: "o26",
        name: "Grimpereau des jardins",
        type: "Passereau",
        done: false,
        constellation: "Certhiidae",
        magnitude: "12-13 cm",
        distance: "Jardins, forets",
      },
      {
        id: "o27",
        name: "Sittelle torchepot",
        type: "Passereau",
        done: false,
        constellation: "Sittidae",
        magnitude: "14 cm",
        distance: "Forets de feuillus",
      },
      {
        id: "o28",
        name: "Pic vert",
        type: "Piciforme",
        done: false,
        constellation: "Picidae",
        magnitude: "31-33 cm",
        distance: "Forets, parcs",
      },
      {
        id: "o29",
        name: "Pic epeiche",
        type: "Piciforme",
        done: false,
        constellation: "Picidae",
        magnitude: "23-26 cm",
        distance: "Forets, jardins",
      },
      {
        id: "o30",
        name: "Pic noir",
        type: "Piciforme",
        done: false,
        constellation: "Picidae",
        magnitude: "45-47 cm",
        distance: "Grandes forets",
      },
      {
        id: "o31",
        name: "Pigeon ramier",
        type: "Columbiforme",
        done: false,
        constellation: "Columbidae",
        magnitude: "68-77 cm",
        distance: "Forets, villes",
      },
      {
        id: "o32",
        name: "Tourterelle des bois",
        type: "Columbiforme",
        done: false,
        constellation: "Columbidae",
        magnitude: "47-55 cm",
        distance: "Bocages, forets claires",
      },
      {
        id: "o33",
        name: "Tourterelle turque",
        type: "Columbiforme",
        done: false,
        constellation: "Columbidae",
        magnitude: "47-58 cm",
        distance: "Villes, villages",
      },
      {
        id: "o34",
        name: "Buse variable",
        type: "Rapace",
        done: false,
        constellation: "Accipitridae",
        magnitude: "113-128 cm",
        distance: "Forets, campagnes",
      },
      {
        id: "o35",
        name: "Faucon crecerelle",
        type: "Rapace",
        done: false,
        constellation: "Falconidae",
        magnitude: "68-78 cm",
        distance: "Campagnes, villes",
      },
      {
        id: "o36",
        name: "Faucon pelerin",
        type: "Rapace",
        done: false,
        constellation: "Falconidae",
        magnitude: "95-115 cm",
        distance: "Falaises, villes",
      },
      {
        id: "o37",
        name: "Epervier d'Europe",
        type: "Rapace",
        done: false,
        constellation: "Accipitridae",
        magnitude: "60-80 cm",
        distance: "Forets, bocages",
      },
      {
        id: "o38",
        name: "Milan noir",
        type: "Rapace",
        done: false,
        constellation: "Accipitridae",
        magnitude: "160-180 cm",
        distance: "Berges, plaines",
      },
      {
        id: "o39",
        name: "Milan royal",
        type: "Rapace",
        done: false,
        constellation: "Accipitridae",
        magnitude: "175-195 cm",
        distance: "Campagnes, forets",
      },
      {
        id: "o40",
        name: "Bondree apivore",
        type: "Rapace",
        done: false,
        constellation: "Accipitridae",
        magnitude: "135-150 cm",
        distance: "Forets, bocages",
      },
      {
        id: "o41",
        name: "Chouette hulotte",
        type: "Rapace nocturne",
        done: false,
        constellation: "Strigidae",
        magnitude: "81-96 cm",
        distance: "Forets, parcs",
      },
      {
        id: "o42",
        name: "Hibou moyen-duc",
        type: "Rapace nocturne",
        done: false,
        constellation: "Strigidae",
        magnitude: "85-100 cm",
        distance: "Forets, bocages",
      },
      {
        id: "o43",
        name: "Effraie des clochers",
        type: "Rapace nocturne",
        done: false,
        constellation: "Tytonidae",
        magnitude: "85-93 cm",
        distance: "Campagnes, villages",
      },
      {
        id: "o44",
        name: "Heron cendre",
        type: "Ardeiforme",
        done: false,
        constellation: "Ardeidae",
        magnitude: "175-195 cm",
        distance: "Berges, etangs",
      },
      {
        id: "o45",
        name: "Grande aigrette",
        type: "Ardeiforme",
        done: false,
        constellation: "Ardeidae",
        magnitude: "140-170 cm",
        distance: "Zones humides",
      },
      {
        id: "o46",
        name: "Cigogne blanche",
        type: "Ciconiiforme",
        done: false,
        constellation: "Ciconiidae",
        magnitude: "195-215 cm",
        distance: "Prairies, villages",
      },
      {
        id: "o47",
        name: "Canard colvert",
        type: "Ansheriforme",
        done: false,
        constellation: "Anatidae",
        magnitude: "81-98 cm",
        distance: "Etangs, rivieres",
      },
      {
        id: "o48",
        name: "Grebe huppe",
        type: "Podicipediforme",
        done: false,
        constellation: "Podicipedidae",
        magnitude: "59-73 cm",
        distance: "Lacs, etangs",
      },
      {
        id: "o49",
        name: "Martin-pecheur",
        type: "Coraciiforme",
        done: false,
        constellation: "Alcedinidae",
        magnitude: "24-26 cm",
        distance: "Berges de rivieres",
      },
      {
        id: "o50",
        name: "Pie bavarde",
        type: "Passereau",
        done: false,
        constellation: "Corvidae",
        magnitude: "52-62 cm",
        distance: "Villes, campagnes",
      },
      {
        id: "o51",
        name: "Geai des chenes",
        type: "Passereau",
        done: false,
        constellation: "Corvidae",
        magnitude: "52-58 cm",
        distance: "Forets, jardins",
      },
      {
        id: "o52",
        name: "Corbeau freux",
        type: "Passereau",
        done: false,
        constellation: "Corvidae",
        magnitude: "81-99 cm",
        distance: "Campagnes, forets",
      },
      {
        id: "o53",
        name: "Corneille noire",
        type: "Passereau",
        done: false,
        constellation: "Corvidae",
        magnitude: "84-100 cm",
        distance: "Villes, campagnes",
      },
      {
        id: "o54",
        name: "Choucas des tours",
        type: "Passereau",
        done: false,
        constellation: "Corvidae",
        magnitude: "65-74 cm",
        distance: "Villes, falaises",
      },
      {
        id: "o55",
        name: "Grand corbeau",
        type: "Passereau",
        done: false,
        constellation: "Corvidae",
        magnitude: "115-130 cm",
        distance: "Montagnes, forets",
      },
      {
        id: "o56",
        name: "Coucou gris",
        type: "Cuculiforme",
        done: false,
        constellation: "Cuculidae",
        magnitude: "55-65 cm",
        distance: "Forets, bocages",
      },
      {
        id: "o57",
        name: "Huppe fasciee",
        type: "Bucerotiforme",
        done: false,
        constellation: "Upupidae",
        magnitude: "42-46 cm",
        distance: "Campagnes, jardins",
      },
      {
        id: "o58",
        name: "Rollier d'Europe",
        type: "Coraciiforme",
        done: false,
        constellation: "Coraciidae",
        magnitude: "52-58 cm",
        distance: "Plaines, garrigues",
      },
      {
        id: "o59",
        name: "Guepier d'Europe",
        type: "Coraciiforme",
        done: false,
        constellation: "Meropidae",
        magnitude: "44-49 cm",
        distance: "Berges sableuses, garrigue",
      },
      {
        id: "o60",
        name: "Courlis cendre",
        type: "Charadriiforme",
        done: false,
        constellation: "Scolopacidae",
        magnitude: "80-100 cm",
        distance: "Prairies humides, cotes",
      },
    ],
  },
];

export async function loadData(): Promise<Domain[]> {
  try {
    const raw = await AsyncStorage.getItem(STORAGE_KEY);
    if (raw) return JSON.parse(raw);
    await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(DEFAULT_DATA));
    return DEFAULT_DATA;
  } catch {
    return DEFAULT_DATA;
  }
}

export async function saveData(data: Domain[]): Promise<void> {
  try {
    await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(data));
  } catch (e) {
    console.error("Erreur sauvegarde:", e);
  }
}

export async function toggleObject(
  domainId: string,
  objectId: string,
  extras?: {
    photoUri?: string;
    date?: string;
    notes?: string;
    location?: { latitude: number; longitude: number };
  },
): Promise<Domain[]> {
  const data = await loadData();
  const domain = data.find((d) => d.id === domainId);
  if (!domain) return data;
  const obj = domain.objects.find((o) => o.id === objectId);
  if (!obj) return data;
  obj.done = !obj.done;
  if (extras) {
    if (extras.location) obj.location = extras.location;
    if (extras.photoUri) obj.photoUri = extras.photoUri;
    if (extras.date) obj.date = extras.date;
    if (extras.notes) obj.notes = extras.notes;
  }
  await saveData(data);
  return data;
}

// Créer un nouveau domaine custom
export async function createDomain(
  label: string,
  icon: string,
  color: string,
): Promise<Domain[]> {
  const data = await loadData();
  const id = "custom_" + Date.now();
  data.push({ id, label, icon, color, objects: [] });
  await saveData(data);
  return data;
}

// Ajouter un objet dans un domaine
export async function addObject(
  domainId: string,
  name: string,
  type: string,
): Promise<Domain[]> {
  const data = await loadData();
  const domain = data.find((d) => d.id === domainId);
  if (!domain) return data;
  const id = domainId + "_" + Date.now();
  domain.objects.push({ id, name, type, done: false });
  await saveData(data);
  return data;
}

// Supprimer un domaine custom
export async function deleteDomain(domainId: string): Promise<Domain[]> {
  const data = await loadData();
  const filtered = data.filter((d) => d.id !== domainId);
  await saveData(filtered);
  return filtered;
}

// Supprimer un objet
export async function deleteObject(
  domainId: string,
  objectId: string,
): Promise<Domain[]> {
  const data = await loadData();
  const domain = data.find((d) => d.id === domainId);
  if (!domain) return data;
  domain.objects = domain.objects.filter((o) => o.id !== objectId);
  await saveData(data);
  return data;
}
