/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/catalogue`; params?: Router.UnknownInputParams; } | { pathname: `/detail`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/stats`; params?: Router.UnknownInputParams; } | { pathname: `/theme/colors`; params?: Router.UnknownInputParams; } | { pathname: `/theme/usetheme`; params?: Router.UnknownInputParams; } | { pathname: `/theme/useTheme`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/storage/catalogue`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/catalogue`; params?: Router.UnknownOutputParams; } | { pathname: `/detail`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/stats`; params?: Router.UnknownOutputParams; } | { pathname: `/theme/colors`; params?: Router.UnknownOutputParams; } | { pathname: `/theme/usetheme`; params?: Router.UnknownOutputParams; } | { pathname: `/theme/useTheme`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/storage/catalogue`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/catalogue${`?${string}` | `#${string}` | ''}` | `/detail${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/stats${`?${string}` | `#${string}` | ''}` | `/theme/colors${`?${string}` | `#${string}` | ''}` | `/theme/usetheme${`?${string}` | `#${string}` | ''}` | `/theme/useTheme${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/storage/catalogue${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/catalogue`; params?: Router.UnknownInputParams; } | { pathname: `/detail`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/stats`; params?: Router.UnknownInputParams; } | { pathname: `/theme/colors`; params?: Router.UnknownInputParams; } | { pathname: `/theme/usetheme`; params?: Router.UnknownInputParams; } | { pathname: `/theme/useTheme`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/storage/catalogue`; params?: Router.UnknownInputParams; };
    }
  }
}
